worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        # Écoute uniquement sur localhost (port 80)
        listen 127.0.0.1:80;
        server_name localhost;

        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}